# Generated by Django 3.1.4 on 2020-12-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greysonmurray', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
